export const copy = {
  app: {
    name: "BeeKas",
    description: "Buy and sell pre-loved items with people nearby.",
  },
  nav: {
    label: "Main navigation",
    catalog: "Catalog",
    post: "Post",
    myListings: "My listings",
    profile: "Profile",
  },
  offline: {
    banner: "You're offline. Some content may be out of date.",
  },
  auth: {
    signIn: {
      title: "Sign in",
      intro: "Use your campus email. We'll send you a 6-digit code.",
      emailLabel: "Campus email",
      emailPlaceholder: "name@binus.ac.id",
      sendCode: "Send code",
      sending: "Sending...",
      codeTitle: "Enter your code",
      codeSentTo: "We sent a 6-digit code to",
      codeLabel: "6-digit code",
      verify: "Verify",
      verifying: "Verifying...",
      resend: "Resend code",
      changeEmail: "Use a different email",
      codeResent: "A new code is on its way.",
    },
    signOut: "Sign out",
    errors: {
      invalid_email: "Enter a valid email address.",
      not_campus_domain: "Use your @binus.ac.id or @binus.edu email.",
      invalid_otp: "That code is wrong or has expired. Check it or request a new one.",
      rate_limited: "Too many attempts. Please wait a minute and try again.",
      generic: "Something went wrong. Please try again.",
    },
  },
  profile: {
    summaryTitle: "Your profile",
    completeTitle: "Complete your profile",
    completeIntro: "Buyers and sellers need a few details before you can post or manage listings.",
    edit: "Edit profile",
    save: "Save profile",
    saving: "Saving...",
    notSet: "Not set",
    incomplete: "Your profile is incomplete.",
    fields: {
      email: "Email",
      userType: "Account type",
      nickname: "Nickname",
      whatsapp: "WhatsApp number",
      whatsappHint: "Example: 0812 3456 7890",
      campus: "Campus",
      campusPlaceholder: "Choose your campus",
      major: "Major",
      majorPlaceholder: "Choose your major",
      majorOther: "Other",
      binusian: "BINUSIAN",
      binusianPlaceholder: "Choose your BINUSIAN",
      binusianHint: "BINUSIAN is your expected graduation year, not your entry year.",
    },
    userTypes: { student: "Student", staff: "Staff" },
    campuses: {
      kemanggisan: "Kemanggisan",
      senayan: "Senayan",
      alam_sutera: "Alam Sutera",
      base: "BASE (BINUS ASO School of Engineering)",
      bekasi: "Bekasi",
      bandung: "Bandung",
      malang: "Malang",
      semarang: "Semarang",
      online: "BINUS Online",
    },
    errors: {
      nickname_required: "Enter a nickname.",
      nickname_too_short: "Nickname must be at least 2 characters.",
      nickname_too_long: "Nickname must be at most 30 characters.",
      invalid_whatsapp: "Enter a valid Indonesian mobile number.",
      invalid_campus: "Choose a campus.",
      major_required: "Choose your major.",
      invalid_major: "Choose a major from the list.",
      binusian_required: "Choose your BINUSIAN.",
      invalid_binusian: "Choose a BINUSIAN from the list.",
      major_not_allowed: "Staff accounts don't have a major.",
      binusian_not_allowed: "Staff accounts don't have a BINUSIAN.",
      save_failed: "Couldn't save your profile. Please try again.",
    },
  },
  credits: {
    title: "Listing credits",
    count: (n: number) => `${n} listing ${n === 1 ? "credit" : "credits"}`,
    rule: "One credit publishes one listing. Credits can't be cashed out or transferred.",
    historyTitle: "Credit history",
    historyEmpty: "No credit changes yet.",
    reasons: {
      purchase: "Purchase",
      listing_publish: "Listing published",
      signup_bonus: "Sign-up bonus",
      admin_adjustment: "Adjustment by admin",
    },
  },
  admin: {
    credits: {
      title: "Adjust listing credits",
      notAdmin: "This page is for admins only.",
      searchLabel: "Find a member by email or nickname",
      search: "Search",
      noResults: "No members found.",
      deltaLabel: "Change (e.g. 5 or -2)",
      noteLabel: "Reason",
      apply: "Apply",
      done: "Credits updated.",
      errors: {
        member_required: "Choose a member.",
        invalid_delta: "Enter a whole number other than 0.",
        note_required: "Write a reason.",
        note_too_long: "Keep the reason under 200 characters.",
        credits_below_zero: "That would take the member below 0 credits.",
        not_admin: "This page is for admins only.",
        member_not_found: "Member not found.",
        generic: "Couldn't update credits. Please try again.",
      },
    },
  },
  listingPhoto: {
    label: "Photo",
    camera: "Take photo",
    choose: "From gallery",
    change: "Change photo",
    warning: "Don't show faces, ID cards, or other personal data in the photo.",
    uploading: "Uploading...",
    uploaded: "Photo uploaded.",
    previewAlt: "Selected listing photo",
    errors: {
      not_image: "Choose an image file.",
      unreadable: "Couldn't read that image. Try another photo.",
      too_large: "That photo is too large even after resizing. Try another one.",
      upload_failed: "Couldn't upload the photo. Please try again.",
    },
  },
  listing: {
    types: { sale: "Sell", donation: "Give away (Free)" },
    categories: { books: "Books", lab: "Lab equipment", electronics: "Electronics", dorm: "Dorm & household", other: "Other" },
    conditions: { like_new: "Like new", good: "Good", used: "Used" },
    free: "Free",
  },
  postForm: {
    fields: {
      type: "Listing type",
      title: "Title",
      category: "Category",
      categoryPlaceholder: "Choose a category",
      condition: "Condition",
      conditionPlaceholder: "Choose a condition",
      description: "Description",
      price: "Price (Rp)",
      priceHint: "Whole rupiah, from Rp1.000 to Rp100.000.000.",
      campus: "Where the item is",
      meetupNote: "Meetup note (optional)",
      meetupNoteHint: "A short hint for COD, e.g. \"Lobby Anggrek after 3 pm\". Only signed-in members see it.",
    },
    statement:
      "I own this item, it is not prohibited (medicine or supplements, food or drinks, cigarettes or vapes, alcohol, weapons, identity documents, pirated goods, adult content, animals), and my profile may be shown to buyers.",
    cost: (credits: number) =>
      `Publishing uses 1 listing credit. You have ${credits} listing ${credits === 1 ? "credit" : "credits"}.`,
    noCredits: "You have no listing credits. Credits are given by an admin for now. Your form stays filled in.",
    publish: "Publish listing",
    publishing: "Publishing...",
    published: "Your listing is live.",
    postAnother: "Post another item",
    errors: {
      invalid_type: "Choose sell or give away.",
      title_too_short: "Title must be at least 3 characters.",
      title_too_long: "Title must be at most 80 characters.",
      invalid_category: "Choose a category.",
      invalid_condition: "Choose a condition.",
      description_required: "Describe the item.",
      description_too_long: "Keep the description under 1000 characters.",
      invalid_price: "Enter a whole number, e.g. 150.000.",
      price_out_of_range: "Price must be between Rp1.000 and Rp100.000.000.",
      invalid_campus: "Choose where the item is.",
      meetup_note_too_long: "Keep the meetup note under 100 characters.",
      photo_required: "Add a photo.",
      agree_required: "Tick the statement to publish.",
      no_credits: "You have no listing credits left.",
      profile_incomplete: "Complete your profile first.",
      photo_missing: "The photo didn't upload. Add it again.",
      generic: "Couldn't publish your listing. Please try again.",
    },
  },
  catalog: {
    searchLabel: "Search listings",
    searchPlaceholder: "Search title or description",
    type: "Type",
    category: "Category",
    campus: "Campus",
    any: "All",
    types: { sale: "For sale", donation: "Free" },
    apply: "Search",
    clear: "Clear filters",
    emptyAll: "No listings yet. Be the first to post an item.",
    postCta: "Post an item",
    emptyResults: "No listings match your search.",
    emptyResultsHint: "Try other words or clear the filters.",
    booked: "Booked",
  },
  pages: {
    catalog: { title: "Catalog" },
    post: { title: "Post an item" },
    myListings: { title: "My listings", empty: "You haven't posted anything yet." },
    profile: { title: "Profile", empty: "Your profile will appear here." },
    offline: { title: "You're offline", empty: "This page isn't available offline. Reconnect and try again." },
  },
} as const;
