/// All UI text, in two maps (D-11). English is the default.
enum Lang { en, id }

// ponytail: global language; the EN|ID toggle ticket makes it persisted and listenable.
Lang currentLang = Lang.en;

String t(String key) => copy[currentLang]![key]!;

const copy = <Lang, Map<String, String>>{
  Lang.en: {
    'back': 'Back',
    'showPassword': 'Show password',
    'hidePassword': 'Hide password',
    'signIn': 'Sign in',
    'register': 'Register',
    'next': 'Next',
    'forgotPassword': 'Forgot password?',
    'password': 'Password',
    'fullName': 'Full name',
    'fullNameHint': 'John Doe',
    'fullNameRequired': 'Enter your full name.',
    'registerDataWarning':
        'Make sure your details are correct and match your BINUS identity.',
    'errorInvalidEmailDomain':
        'Use your BINUS email (@binus.ac.id or @binus.edu).',
    'errorAccountTypeNotAllowed':
        'Account type is set automatically for @binus.ac.id.',
    'errorAccountTypeRequired': 'Choose Lecturer or Staff.',
    'errorInvalidCampus': 'Choose your campus.',
    'errorPhoneRequired': 'Enter your phone number.',
    'errorInvalidPhone': 'Enter a valid phone number.',
    'errorPhoneTaken': 'This phone number is already registered.',
    'errorPhoneMissing': 'Add your phone number before sending for review.',
    'errorSignupUnknown': 'Registration failed. Please try again.',
    'registerTitle': 'Your details',
    'registerSubtitle': 'Fill in the details below to continue registering.',
    'registerStep': 'Step {n} of 3',
    'emailBinus': 'BINUS email',
    'emailHint': 'john.doe@binus.ac.id',
    'phone': 'Phone number',
    'phoneHint': '+62 812 3456 7890',
    'accountType': 'Account type',
    'accountTypeHint': 'Choose Lecturer or Staff',
    'accountType_student': 'Student',
    'accountType_lecturer': 'Lecturer',
    'accountType_staff': 'Staff',
    'campus': 'Campus',
    'campusHint': 'Choose your campus',
    'campus_kemanggisan': 'Kampus Binus Kemanggisan',
    'campus_senayan': 'Kampus Binus Senayan',
    'campus_alam_sutera': 'Kampus Binus Alam Sutera',
    'campus_base': 'Kampus Binus BASE',
    'campus_bekasi': 'Kampus Binus Bekasi',
    'campus_bandung': 'Kampus Binus Bandung',
    'campus_malang': 'Kampus Binus Malang',
    'campus_semarang': 'Kampus Binus Semarang',
    'campus_online': 'BINUS Online',
    'errorEmailRequired': 'Enter your BINUS email.',
    'errorNetwork':
        "Can't reach the server. Check your connection and try again.",
    'codeSent': 'We sent a 6-digit code to your email.',
    'errorInvalidCode': 'The code is wrong or has expired.',
    'errorTooSoon': 'Please wait before requesting a new code.',
    'errorWeakPassword': "The password doesn't meet the requirements yet.",
    'otpTitle': 'Verify your email',
    'otpSubtitle': 'Enter the 6-digit code we sent to {email}.',
    'otpCode': 'Verification code',
    'otpHint': '123456',
    'errorCodeRequired': 'Enter the 6-digit code.',
    'verify': 'Verify',
    'resendCode': 'Resend code',
    'resendIn': 'Resend in {s}s',
    'emailRegistered': 'This email is already registered. Sign in instead.',
    'phoneTitle': 'Phone number',
    'phoneSubtitle': "Your phone number hasn't been saved yet. Enter another number to continue.",
    'phoneKept': 'The phone number {phone} from your earlier registration is kept, not the one you just entered.',
    'passwordTitle': 'Create a password',
    'passwordSubtitle': "You'll use this password to sign in to BeeKas.",
    'passwordConfirm': 'Confirm password',
    'passwordHelper': "Don't use your Binusmaya password or any other account's. Create a password just for BeeKas.",
    'ruleMinLength': 'At least 8 characters',
    'ruleLetter': 'Contains a letter',
    'ruleDigit': 'Contains a number',
    'ruleMatch': 'Matches the confirmation',
    'passwordSaved': 'Password saved.',
  },
  Lang.id: {
    'back': 'Kembali',
    'showPassword': 'Tampilkan kata sandi',
    'hidePassword': 'Sembunyikan kata sandi',
    'signIn': 'Masuk',
    'register': 'Daftar',
    'next': 'Lanjut',
    'forgotPassword': 'Lupa kata sandi?',
    'password': 'Kata sandi',
    'fullName': 'Nama lengkap',
    'fullNameHint': 'John Doe',
    'fullNameRequired': 'Isi nama lengkap.',
    'registerDataWarning':
        'Pastikan data sudah benar dan sesuai identitas BINUS.',
    'errorInvalidEmailDomain':
        'Gunakan email BINUS (@binus.ac.id atau @binus.edu).',
    'errorAccountTypeNotAllowed':
        'Tipe akun untuk @binus.ac.id ditentukan otomatis.',
    'errorAccountTypeRequired': 'Pilih Dosen atau Staf.',
    'errorInvalidCampus': 'Pilih kampus asal.',
    'errorPhoneRequired': 'Isi nomor HP.',
    'errorInvalidPhone': 'Masukkan nomor HP yang valid.',
    'errorPhoneTaken': 'Nomor HP ini sudah terdaftar.',
    'errorPhoneMissing': 'Isi nomor HP sebelum mengirim untuk diperiksa.',
    'errorSignupUnknown': 'Pendaftaran gagal. Coba lagi.',
    'registerTitle': 'Isi Data Diri',
    'registerSubtitle':
        'Lengkapi informasi berikut untuk melanjutkan pendaftaran.',
    'registerStep': 'Langkah {n} dari 3',
    'emailBinus': 'Email BINUS',
    'emailHint': 'john.doe@binus.ac.id',
    'phone': 'Nomor Handphone',
    'phoneHint': '+62 812 3456 7890',
    'accountType': 'Tipe Akun',
    'accountTypeHint': 'Pilih Dosen atau Staf',
    'accountType_student': 'Mahasiswa',
    'accountType_lecturer': 'Dosen',
    'accountType_staff': 'Staf',
    'campus': 'Kampus Asal',
    'campusHint': 'Pilih kampus asal',
    'campus_kemanggisan': 'Kampus Binus Kemanggisan',
    'campus_senayan': 'Kampus Binus Senayan',
    'campus_alam_sutera': 'Kampus Binus Alam Sutera',
    'campus_base': 'Kampus Binus BASE',
    'campus_bekasi': 'Kampus Binus Bekasi',
    'campus_bandung': 'Kampus Binus Bandung',
    'campus_malang': 'Kampus Binus Malang',
    'campus_semarang': 'Kampus Binus Semarang',
    'campus_online': 'BINUS Online',
    'errorEmailRequired': 'Isi email BINUS.',
    'errorNetwork':
        'Tidak bisa terhubung ke server. Periksa koneksi lalu coba lagi.',
    'codeSent': 'Kode 6 digit sudah dikirim ke email kamu.',
    'errorInvalidCode': 'Kode salah atau sudah kedaluwarsa.',
    'errorTooSoon': 'Tunggu sebentar sebelum meminta kode baru.',
    'errorWeakPassword': 'Kata sandi belum memenuhi syarat.',
    'otpTitle': 'Verifikasi Email',
    'otpSubtitle': 'Masukkan kode 6 digit yang dikirim ke {email}.',
    'otpCode': 'Kode verifikasi',
    'otpHint': '123456',
    'errorCodeRequired': 'Isi kode 6 digit.',
    'verify': 'Verifikasi',
    'resendCode': 'Kirim ulang kode',
    'resendIn': 'Kirim ulang dalam {s} dtk',
    'emailRegistered': 'Email ini sudah terdaftar. Silakan masuk.',
    'phoneTitle': 'Nomor Handphone',
    'phoneSubtitle':
        'Nomor HP kamu belum tersimpan. Masukkan nomor lain untuk melanjutkan.',
    'phoneKept': 'Nomor HP {phone} dari pendaftaran sebelumnya tetap dipakai, bukan nomor yang baru diisi.',
    'passwordTitle': 'Buat Kata Sandi',
    'passwordSubtitle': 'Kata sandi ini dipakai untuk masuk ke BeeKas.',
    'passwordConfirm': 'Konfirmasi kata sandi',
    'passwordHelper': 'Jangan gunakan kata sandi Binusmaya atau akun lain. Buat kata sandi khusus untuk BeeKas.',
    'ruleMinLength': 'Minimal 8 karakter',
    'ruleLetter': 'Ada huruf',
    'ruleDigit': 'Ada angka',
    'ruleMatch': 'Sama dengan konfirmasi',
    'passwordSaved': 'Kata sandi tersimpan.',
  },
};
